### ISSUE TITLE
🐞 Error al procesar los porcentajes del catálogo c_TasaOCuota.json

### ISSUE THREAD

**Issue by lcarrasco** [bambucode/catalogos_sat#1]
Referencia:
https://github.com/bambucode/catalogos_sat_JSON/pull/1

Creo que el error puede ir por la función que convierte a decimales que solo toma en cuenta el entero e ignora los decimales.

**Comment by ricardo-trevizo-b** [comment]
Fixed in 2319db52cf55678ec54851392b51225abdf84f92

**Comment by lcarrasco** [comment]
👍🏻
