### ISSUE TITLE
Actualización 2018-06-18

### ISSUE THREAD

**Issue by eclipxe13** [bambucode/catalogos_sat#2]
El día de ayer 2018-06-18 se publicó una nueva actualización de los catálogos.

Parece que el sitio del SAT está en actualización por lo que las direcciones anteriores no funcionan bien. La información la pueden encontrar en:

http://omawww.sat.gob.mx/informacion_fiscal/factura_electronica/Paginas/Anexo_20_version3.3.aspx

http://omawww.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/catCFDI.xls

**Comment by jiagbrody** [comment]
Deberian de cerrar este issue.
Saludos
